### ISSUE TITLE
Add styles for the short codes

### ISSUE THREAD

**Issue by JordanJordanov** [gardener/website-generator#95]
**What happened**:
The websites with Docsy theme does not format correctly the short codes, e.g. notice note in https://github.com/gardener/documentation/issues/123

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

**Comment by Kristian-ZH** [comment]
Actually I do not see much value in supporting such a short codes. If the user reads the documentation directly from Gthub, the short codes will not work: https://github.com/gardener/documentation/blob/master/website/documentation/guides/administer_shoots/maintain-shoot/_index.md

My suggestion is to use proper markdown tags instead of supporting such a short codes.

**Comment by JordanJordanov** [comment]
The idea here is to support a very limited subset of short codes - the ones with highest value (like Info & warning box)

**Comment by JordanJordanov** [comment]
closed with https://github.com/gardener/documentation/pull/272
